--- 
- debug: msg="Playbook source {{ playbook_source }} "

# debugging variables
- include: debug.yml
  when: debug

# reload-systemd
- meta: flush_handlers

- name: Enable kubelet
  service:
    name: kubelet
    enabled: yes
